### ISSUE TITLE
Premature Close Exception on my machine ...

### ISSUE THREAD

**Issue by hl191** [mguenther/spring-workshop-spring-cloud-gateway#1]
```2023-05-11T15:10:55.743+02:00 TRACE 24076 --- [ctor-http-nio-4] o.s.c.g.f.WeightCalculatorWebFilter      : Weights attr: {}
2023-05-11T15:10:55.744+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.c.g.h.RoutePredicateHandlerMapping   : Route matched: command-service
2023-05-11T15:10:55.744+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.c.g.h.RoutePredicateHandlerMapping   : Mapping [Exchange: POST http://localhost:8080/api/items] to Route{id='command-service', uri=http://localhost:8089, order=0, predicate=Methods: [POST, PUT, DELETE], gatewayFilters=[], metadata={}}
2023-05-11T15:10:55.744+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.c.g.h.RoutePredicateHandlerMapping   : [e000fccb-2] Mapped to org.springframework.cloud.gateway.handler.FilteringWebHandler@4807c291
2023-05-11T15:10:55.744+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.c.g.handler.FilteringWebHandler      : Sorted gatewayFilterFactories: [[GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter@b5c6a30}, order = -2147483648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.AdaptCachedBodyGlobalFilter@79476a4e}, order = -2147482648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyWriteResponseFilter@49433c98}, order = -1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardPathFilter@47829d6d}, order = 0], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.GatewayMetricsFilter@43f03c23}, order = 0], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter@3bfae028}, order = 10000], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.config.GatewayNoLoadBalancerClientAutoConfiguration$NoLoadBalancerClientFilter@7a1b8a46}, order = 10150], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.WebsocketRoutingFilter@2f677247}, order = 2147483646], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyRoutingFilter@1ca610a0}, order = 2147483647], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardRoutingFilter@1775c4e7}, order = 2147483647]]
2023-05-11T15:10:55.746+02:00 TRACE 24076 --- [ctor-http-nio-4] o.s.c.g.filter.RouteToRequestUrlFilter   : RouteToRequestUrlFilter start
2023-05-11T15:10:55.752+02:00 DEBUG 24076 --- [ctor-http-nio-4] g.f.h.o.ObservedRequestHttpHeadersFilter : Will instrument the HTTP request headers [Content-Type:"application/json", User-Agent:"PostmanRuntime/7.32.2", Accept:"*/*", Postman-Token:"ca9209b8-b3ef-4231-9b33-48f1b091cea0", Host:"localhost:8080", Accept-Encoding:"gzip, deflate, br", Content-Length:"38", Forwarded:"proto=http;host="localhost:8080";for="[0:0:0:0:0:0:0:1]:63405"", X-Forwarded-For:"0:0:0:0:0:0:0:1", X-Forwarded-Proto:"http", X-Forwarded-Port:"8080", X-Forwarded-Host:"localhost:8080"]
2023-05-11T15:10:55.755+02:00 DEBUG 24076 --- [ctor-http-nio-4] g.f.h.o.ObservedRequestHttpHeadersFilter : Client observation  {name=http.client.requests(null), error=null, context=name='http.client.requests', contextualName='null', error='null', lowCardinalityKeyValues=[http.method='POST', http.status_code='UNKNOWN', spring.cloud.gateway.route.id='command-service', spring.cloud.gateway.route.uri='http://localhost:8089'], highCardinalityKeyValues=[http.uri='http://localhost:8080/api/items'], map=[class io.micrometer.core.instrument.LongTaskTimer$Sample='SampleImpl{duration(seconds)=2.957E-4, duration(nanos)=295700.0, startTimeNanos=8966954574100}', class io.micrometer.core.instrument.Timer$Sample='io.micrometer.core.instrument.Timer$Sample@e18dc77'], parentObservation={name=http.server.requests(null), error=null, context=name='http.server.requests', contextualName='null', error='null', lowCardinalityKeyValues=[exception='none', method='POST', outcome='SUCCESS', status='200', uri='UNKNOWN'], highCardinalityKeyValues=[http.url='/api/items'], map=[class io.micrometer.core.instrument.LongTaskTimer$Sample='SampleImpl{duration(seconds)=0.0113999, duration(nanos)=1.13999E7, startTimeNanos=8966943551000}', class io.micrometer.core.instrument.Timer$Sample='io.micrometer.core.instrument.Timer$Sample@3af37926'], parentObservation=null}} created for the request. New headers are [Content-Type:"application/json", User-Agent:"PostmanRuntime/7.32.2", Accept:"*/*", Postman-Token:"ca9209b8-b3ef-4231-9b33-48f1b091cea0", Host:"localhost:8080", Accept-Encoding:"gzip, deflate, br", Content-Length:"38", Forwarded:"proto=http;host="localhost:8080";for="[0:0:0:0:0:0:0:1]:63405"", X-Forwarded-For:"0:0:0:0:0:0:0:1", X-Forwarded-Proto:"http", X-Forwarded-Port:"8080", X-Forwarded-Host:"localhost:8080"]
2023-05-11T15:10:55.775+02:00 DEBUG 24076 --- [ctor-http-nio-4] i.n.r.DefaultHostsFileEntriesResolver    : -Dio.netty.hostsFileRefreshInterval: 0
2023-05-11T15:10:55.785+02:00 DEBUG 24076 --- [ctor-http-nio-4] .d.DefaultDnsServerAddressStreamProvider : Default DNS servers: [/10.0.0.1:53, /192.168.0.1:53, /10.0.7.254:53] (sun.net.dns.ResolverConfiguration)
2023-05-11T15:10:55.787+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.resources.PooledConnectionProvider   : Creating a new [proxy] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=2147483647, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=-1, pendingAcquireTimeout=0}] for [localhost/<unresolved>:8089]
2023-05-11T15:10:55.795+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.resources.PooledConnectionProvider   : [d115b197] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2023-05-11T15:10:55.797+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.netty.transport.TransportConfig        : [d115b197] Initialized pipeline DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2023-05-11T15:10:55.819+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.netty.transport.TransportConnector     : [d115b197] Connecting to [localhost/127.0.0.1:8089].
2023-05-11T15:10:55.821+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [d115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] Registering pool release on close event for channel
2023-05-11T15:10:55.822+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.resources.PooledConnectionProvider   : [d115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
2023-05-11T15:10:55.822+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [d115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] onStateChange(PooledConnection{channel=[id: 0xd115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089]}, [connected])
2023-05-11T15:10:55.824+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [d115b197-1, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] onStateChange(GET{uri=null, connection=PooledConnection{channel=[id: 0xd115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089]}}, [configured])
2023-05-11T15:10:55.824+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.netty.http.client.HttpClientConnect    : [d115b197-1, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] Handler is being applied: {uri=http://localhost:8089/api/items, method=POST}
2023-05-11T15:10:55.824+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [d115b197-1, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089] onStateChange(POST{uri=/api/items, connection=PooledConnection{channel=[id: 0xd115b197, L:/127.0.0.1:63406 - R:localhost/127.0.0.1:8089]}}, [request_prepared])
2023-05-11T15:10:55.825+02:00 TRACE 24076 --- [ctor-http-nio-4] o.s.c.gateway.filter.NettyRoutingFilter  : outbound route: d115b197, inbound: [e000fccb-2] 
2023-05-11T15:10:55.830+02:00 DEBUG 24076 --- [ctor-http-nio-4] reactor.netty.channel.FluxReceive        : [e000fccb-1, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:63405] [terminated=true, cancelled=false, pending=1, error=null]: subscribing inbound receiver
2023-05-11T15:10:55.831+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.resources.PooledConnectionProvider   : [d115b197-1, L:/127.0.0.1:63406 ! R:localhost/127.0.0.1:8089] Channel closed, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2023-05-11T15:10:55.831+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.netty.channel.ChannelOperations        : [e000fccb-1, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:63405] [HttpServer] Channel inbound receiver cancelled (operation cancelled).
2023-05-11T15:10:55.831+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [d115b197-1, L:/127.0.0.1:63406 ! R:localhost/127.0.0.1:8089] onStateChange(POST{uri=/api/items, connection=PooledConnection{channel=[id: 0xd115b197, L:/127.0.0.1:63406 ! R:localhost/127.0.0.1:8089]}}, [response_incomplete])
2023-05-11T15:10:55.831+02:00  WARN 24076 --- [ctor-http-nio-4] r.netty.http.client.HttpClientConnect    : [d115b197-1, L:/127.0.0.1:63406 ! R:localhost/127.0.0.1:8089] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body

2023-05-11T15:10:55.833+02:00 DEBUG 24076 --- [ctor-http-nio-4] .o.ObservationClosingWebExceptionHandler : An exception occurred and observation was not previously stopped, will stop it. The exception was [reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body]
2023-05-11T15:10:55.834+02:00 DEBUG 24076 --- [ctor-http-nio-4] a.w.r.e.AbstractErrorWebExceptionHandler : [e000fccb-2] Resolved [PrematureCloseException: Connection has been closed BEFORE response, while sending request body] for HTTP POST /api/items
2023-05-11T15:10:55.834+02:00 ERROR 24076 --- [ctor-http-nio-4] a.w.r.e.AbstractErrorWebExceptionHandler : [e000fccb-2]  500 Server Error for HTTP POST "/api/items"

reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/api/items" [ExceptionHandlingWebHandler]
Original Stack Trace:

2023-05-11T15:10:55.837+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.http.codec.json.Jackson2JsonEncoder  : [e000fccb-2] Encoding [{timestamp=Thu May 11 15:10:55 CEST 2023, path=/api/items, status=500, error=Internal Server Error,  (truncated)...]
2023-05-11T15:10:55.841+02:00 TRACE 24076 --- [ctor-http-nio-4] o.s.c.g.filter.GatewayMetricsFilter      : spring.cloud.gateway.requests tags: [tag(httpMethod=POST),tag(httpStatusCode=500),tag(outcome=SERVER_ERROR),tag(routeId=command-service),tag(routeUri=http://localhost:8089),tag(status=INTERNAL_SERVER_ERROR)]
2023-05-11T15:10:55.842+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [e000fccb-1, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:63405] Decreasing pending responses, now 0
2023-05-11T15:10:55.842+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [e000fccb-1, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:63405] Last HTTP packet was sent, terminating the channel
2023-05-11T15:10:55.842+02:00 DEBUG 24076 --- [ctor-http-nio-4] o.s.w.s.adapter.HttpWebHandlerAdapter    : [e000fccb-2] Completed 500 INTERNAL_SERVER_ERROR
2023-05-11T15:10:55.842+02:00 DEBUG 24076 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [e000fccb-1, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:63405] Last HTTP response frame
```

**Comment by hl191** [comment]
Dockerized Log:

```
2023-05-11 15:33:28 2023-05-11T13:33:28.604Z DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping   : Route matched: command-service
2023-05-11 15:33:28 2023-05-11T13:33:28.606Z DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping   : Mapping [Exchange: POST http://localhost:8080/command-service/api/items] to Route{id='command-service', uri=http://localhost:8089, order=0, predicate=Paths: [/command-service/**], match trailing slash: true, gatewayFilters=[[[RewritePath /command-service/(?<remaining>.*) = '/${remaining}'], order = 1]], metadata={}}
2023-05-11 15:33:28 2023-05-11T13:33:28.606Z DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping   : [f8ed7ba2-1] Mapped to org.springframework.cloud.gateway.handler.FilteringWebHandler@3ece3d31
2023-05-11 15:33:28 2023-05-11T13:33:28.607Z DEBUG 1 --- [or-http-epoll-2] o.s.c.g.handler.FilteringWebHandler      : Sorted gatewayFilterFactories: [[GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter@7adf16aa}, order = -2147483648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.AdaptCachedBodyGlobalFilter@239b0f9d}, order = -2147482648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyWriteResponseFilter@16f7b4af}, order = -1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardPathFilter@73c60324}, order = 0], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.GatewayMetricsFilter@4ba534b0}, order = 0], [[RewritePath /command-service/(?<remaining>.*) = '/${remaining}'], order = 1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter@34a1d21f}, order = 10000], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.config.GatewayNoLoadBalancerClientAutoConfiguration$NoLoadBalancerClientFilter@6f0ca692}, order = 10150], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.WebsocketRoutingFilter@71ae31b0}, order = 2147483646], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyRoutingFilter@6731787b}, order = 2147483647], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardRoutingFilter@58bf8650}, order = 2147483647]]
2023-05-11 15:33:28 2023-05-11T13:33:28.615Z TRACE 1 --- [or-http-epoll-2] o.s.c.g.filter.RouteToRequestUrlFilter   : RouteToRequestUrlFilter start
2023-05-11 15:33:28 2023-05-11T13:33:28.624Z DEBUG 1 --- [or-http-epoll-2] g.f.h.o.ObservedRequestHttpHeadersFilter : Will instrument the HTTP request headers [Content-Type:"application/json", User-Agent:"PostmanRuntime/7.32.2", Accept:"*/*", Postman-Token:"5200d103-36de-4067-8c7d-b1729dc189d4", Host:"localhost:8080", Accept-Encoding:"gzip, deflate, br", Content-Length:"38", Forwarded:"proto=http;host="localhost:8080";for="172.20.0.1:45166"", X-Forwarded-For:"172.20.0.1", X-Forwarded-Proto:"http", X-Forwarded-Prefix:"/command-service", X-Forwarded-Port:"8080", X-Forwarded-Host:"localhost:8080"]
2023-05-11 15:33:28 2023-05-11T13:33:28.627Z DEBUG 1 --- [or-http-epoll-2] g.f.h.o.ObservedRequestHttpHeadersFilter : Client observation  {name=http.client.requests(null), error=null, context=name='http.client.requests', contextualName='null', error='null', lowCardinalityKeyValues=[http.method='POST', http.status_code='UNKNOWN', spring.cloud.gateway.route.id='command-service', spring.cloud.gateway.route.uri='http://localhost:8089'], highCardinalityKeyValues=[http.uri='http://localhost:8080/api/items'], map=[class io.micrometer.core.instrument.LongTaskTimer$Sample='SampleImpl{duration(seconds)=5.97999E-4, duration(nanos)=597999.0, startTimeNanos=10190569481581}', class io.micrometer.core.instrument.Timer$Sample='io.micrometer.core.instrument.Timer$Sample@7a5bcf78'], parentObservation={name=http.server.requests(null), error=null, context=name='http.server.requests', contextualName='null', error='null', lowCardinalityKeyValues=[exception='none', method='POST', outcome='SUCCESS', status='200', uri='UNKNOWN'], highCardinalityKeyValues=[http.url='/command-service/api/items'], map=[class io.micrometer.core.instrument.LongTaskTimer$Sample='SampleImpl{duration(seconds)=0.032969862, duration(nanos)=3.2969862E7, startTimeNanos=10190537300612}', class io.micrometer.core.instrument.Timer$Sample='io.micrometer.core.instrument.Timer$Sample@55aa9d38'], parentObservation=null}} created for the request. New headers are [Content-Type:"application/json", User-Agent:"PostmanRuntime/7.32.2", Accept:"*/*", Postman-Token:"5200d103-36de-4067-8c7d-b1729dc189d4", Host:"localhost:8080", Accept-Encoding:"gzip, deflate, br", Content-Length:"38", Forwarded:"proto=http;host="localhost:8080";for="172.20.0.1:45166"", X-Forwarded-For:"172.20.0.1", X-Forwarded-Proto:"http", X-Forwarded-Prefix:"/command-service", X-Forwarded-Port:"8080", X-Forwarded-Host:"localhost:8080"]
2023-05-11 15:33:28 2023-05-11T13:33:28.694Z DEBUG 1 --- [or-http-epoll-2] .o.ObservationClosingWebExceptionHandler : An exception occurred and observation was not previously stopped, will stop it. The exception was [io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8089]
2023-05-11 15:33:28 2023-05-11T13:33:28.708Z ERROR 1 --- [or-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [f8ed7ba2-1]  500 Server Error for HTTP POST "/command-service/api/items"
2023-05-11 15:33:28 
2023-05-11 15:33:28 io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8089
2023-05-11 15:33:28     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2023-05-11 15:33:28 Error has been observed at the following site(s):
2023-05-11 15:33:28     *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
2023-05-11 15:33:28     *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
2023-05-11 15:33:28     *__checkpoint ⇢ HTTP POST "/command-service/api/items" [ExceptionHandlingWebHandler]
2023-05-11 15:33:28 Original Stack Trace:
2023-05-11 15:33:28 Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
2023-05-11 15:33:28     at io.netty.channel.unix.Errors.newConnectException0(Errors.java:164) ~[netty-transport-native-unix-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:129) ~[netty-transport-native-unix-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[netty-transport-native-unix-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-classes-epoll-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-classes-epoll-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489) ~[netty-transport-classes-epoll-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.90.Final.jar!/:4.1.90.Final]
2023-05-11 15:33:28     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-05-11 15:33:28 
2023-05-11 15:33:28 2023-05-11T13:33:28.743Z TRACE 1 --- [or-http-epoll-2] o.s.c.g.filter.GatewayMetricsFilter      : spring.cloud.gateway.requests tags: [tag(httpMethod=POST),tag(httpStatusCode=500),tag(outcome=SERVER_ERROR),tag(routeId=command-service),tag(routeUri=http://localhost:8089),tag(status=INTERNAL_SERVER_ERROR)]
```
